console.log("I'm just here so I don't get fined.");

const matchupsWrapper = document.getElementById('matchups-wrapper');
const leaguesSelect = document.querySelector<HTMLSelectElement>('#league-select');
const weeksSelect = document.querySelector<HTMLSelectElement>('#week-select');
let snapshotMatchupWrapper: Node | null = null;

// these elements must exist for the page to work, instead of throwing an error, we can redir to 4xx or 5xx
// probably 5xx since the initial html is generated by the server
if (!matchupsWrapper) throw new Error("matchups-wrapper element is missing");
if (!leaguesSelect) throw new Error("league-select element is missing");
if (!weeksSelect) throw new Error("week-select element is missing");

type MatchupsResponse = {
    matchups: MatchupTuple[];
};

type MatchupRow = {
    season: string;
    week: number;
    matchupId: number | null;
    team: string | null;
    owner: string;
    points: string;
    rosterPlayers: {
        playerName: string;
        position: string;
        points: string;
        starter: boolean;
    }[];
};

type MatchupTuple = [MatchupRow, MatchupRow];

window.addEventListener("DOMContentLoaded", async (event) => {
    snapshotMatchupWrapper = matchupsWrapper.cloneNode(true);
});

window.addEventListener("popstate", (event) => {
    // if this condition is met then that means the user has navigated to the initial render of /matchups
    if (!event.state) {
        if (!snapshotMatchupWrapper)
            throw new Error('Error replacing initial state of page');
        // introduce initial snapshot of matchups on DOMContentLoaded
        return matchupsWrapper.replaceWith(snapshotMatchupWrapper);
    }
    const matchupsData: MatchupsData = event.state;
    const { leagueId, weekValue, resourceURL, matchups } = matchupsData;
    renderMatchupsSection(matchups);
    updateSelectedOption(leaguesSelect!, leagueId!);
});

leaguesSelect.addEventListener("change", onLeagueChange);

weeksSelect.addEventListener("change", function () {
    const leagueId = leaguesSelect?.value;
    const weekValue = this.value;
    location.href = location.origin + `/matchups/leagues/${leagueId}/weeks/${weekValue}`;
});

async function onLeagueChange() {
    const matchupsData = await readAndFetchMatchupData();
    const { leagueId, weekValue, resourceURL, matchups } = matchupsData;
    renderMatchupsSection(matchups);
    updateHistoryState(resourceURL, matchupsData);
    updateSelectedOption(leaguesSelect!, leagueId!);
}

function renderMatchupsSection(matchups: MatchupTuple[]) {
    let html = "";
    matchups.forEach(matchup => html += renderMatchupCard(matchup));
    matchupsWrapper!.innerHTML = html;
}

function renderMatchupCard(matchup: MatchupTuple) {
    const [awayTeam, homeTeam] = matchup;

    return `
        <div class="matchup-card">
            <div class="home-team">
                <h2>${escapeHTML(hasTeamName(homeTeam))}</h2>
                <p>${escapeHTML(homeTeam.points)}</p>
            </div>
            <span>vs</span>
            <div class="away-team">
                <h2>${escapeHTML(hasTeamName(awayTeam))}</h2>
                <p>${escapeHTML(awayTeam.points)}</p>
            </div>
        </div>
    `;
}

type MatchupsData = {
    leagueId: string | undefined;
    weekValue: string | undefined;
    resourceURL: string;
    matchups: MatchupTuple[];
};

async function readAndFetchMatchupData() {
    const leagueId = leaguesSelect?.value;
    const weekValue = weeksSelect?.value;
    const resourceURL = `/api/matchups/leagues/${leagueId}/weeks/${weekValue}`;
    const { matchups } = await fetchJSON<MatchupsResponse>(resourceURL);

    return {
        leagueId,
        weekValue,
        resourceURL,
        matchups
    };
}

function updateHistoryState(resourceURL: string, data: MatchupsData) {
    // removes the /api/ prefix on the resource to represent path on front end, see -> readAndFetchMatchupData()
    const updatedURL = resourceURL.slice(4);
    return history.pushState(data, "", updatedURL);
}

// the reason we only update the value and not the selected attribute is that the browser internally handles
// the selected value of a select element, making the browser own the state.
// we could manually update the selected attribute but for now we will not.
// unlike a nav menu, where we would have to update the state manually by adding a class, as a comparison.
function updateSelectedOption(selectElement: HTMLSelectElement, value: string) {
    return selectElement.value = value;
}

function hasTeamName(t: MatchupRow) {
    return t.team ? t.team : t.owner;
}

async function fetchJSON<T>(url: string): Promise<T> {
    const response = await fetch(url);

    if (!response.ok) {
        throw new Error(`HTTP ${response.status} at ${url}`);
    }

    const contentType = response.headers.get('content-type') || '';
    if (!contentType.includes('application/json')) {
        throw new Error(`Expected JSON, received ${contentType}`);
    }

    return await response.json();
}

function escapeHTML(str: string) {
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}